/**
 * Output moderation tests. Every AI output passes through this before publish.
 */
import { describe, it, expect } from "vitest";
import { moderate } from "./moderate";

describe("moderate() — people-group attacks (BLOCK)", () => {
  it("blocks 'Muslims are evil'", () => {
    const r = moderate("Muslims are evil terrorists");
    expect(r.pass).toBe(false);
    expect(r.violations.some((v) => v.category === "people_group_attack")).toBe(true);
  });

  it("blocks 'Jews are christ-killers'", () => {
    const r = moderate("The Jews are christ-killers");
    expect(r.pass).toBe(false);
  });

  it("blocks 'Catholics are not Christians'", () => {
    const r = moderate("Catholics are not Christians");
    expect(r.pass).toBe(false);
  });

  it("blocks 'atheists are fools'", () => {
    const r = moderate("Atheists are fools who hate God");
    expect(r.pass).toBe(false);
  });
});

describe("moderate() — prosperity manipulation (BLOCK)", () => {
  it("blocks 'if you truly trust God, give'", () => {
    const r = moderate("If you truly trust God, give now to this ministry");
    expect(r.pass).toBe(false);
    expect(r.violations.some((v) => v.category === "prosperity_manipulation")).toBe(true);
  });

  it("blocks 'sow a seed of $'", () => {
    const r = moderate("Sow a seed of $100 today");
    expect(r.pass).toBe(false);
  });

  it("blocks 'God will multiply your gift 100'", () => {
    const r = moderate("God will multiply your gift 100x");
    expect(r.pass).toBe(false);
  });
});

describe("moderate() — fresh revelation (BLOCK)", () => {
  it("blocks 'God told me to tell you'", () => {
    const r = moderate("God told me to tell you that you will be healed");
    expect(r.pass).toBe(false);
    expect(r.violations.some((v) => v.category === "fresh_revelation")).toBe(true);
  });

  it("blocks 'thus saith the Lord'", () => {
    const r = moderate("Thus saith the Lord, you shall prosper");
    expect(r.pass).toBe(false);
  });
});

describe("moderate() — tech stack leak (WARN, not block)", () => {
  it("warns on 'Cerebras'", () => {
    const r = moderate("This was generated by Cerebras");
    expect(r.pass).toBe(true); // warn doesn't fail pass
    expect(r.violations.some((v) => v.category === "tech_stack_leak")).toBe(true);
  });

  it("warns on 'Anthropic'", () => {
    const r = moderate("Our system uses Anthropic Claude");
    expect(r.violations.some((v) => v.category === "tech_stack_leak")).toBe(true);
  });

  it("warns on 'Postiz'", () => {
    const r = moderate("We schedule via Postiz");
    expect(r.violations.some((v) => v.category === "tech_stack_leak")).toBe(true);
  });
});

describe("moderate() — personal salvation claims (BLOCK)", () => {
  it("blocks 'you are going to hell'", () => {
    const r = moderate("You are going to hell for that question");
    expect(r.pass).toBe(false);
  });

  it("blocks 'I know you are saved'", () => {
    const r = moderate("I know you are saved because of your prayer");
    expect(r.pass).toBe(false);
  });
});

describe("moderate() — date setting (BLOCK)", () => {
  it("blocks 'Jesus will return in 2030'", () => {
    const r = moderate("Jesus will return in 2030");
    expect(r.pass).toBe(false);
  });

  it("blocks 'the rapture is coming in 2027'", () => {
    const r = moderate("The rapture is coming in 2027");
    expect(r.pass).toBe(false);
  });
});

describe("moderate() — clean output passes", () => {
  it("passes a normal sermon excerpt", () => {
    const r = moderate(
      "Christ is the hope of glory. He died for our sins and rose on the third day. " +
        "Come to him with your burdens, and he will give you rest."
    );
    expect(r.pass).toBe(true);
    expect(r.violations).toHaveLength(0);
  });

  it("passes a scripture quotation", () => {
    const r = moderate(
      "For the earth shall be filled with the knowledge of the glory of the Lord, " +
        "as the waters cover the sea. — Habakkuk 2:14 (WEB)"
    );
    expect(r.pass).toBe(true);
  });

  it("passes a charitable apologetic response", () => {
    const r = moderate(
      "Christians and Muslims both believe in one God, but we differ on the identity of Jesus. " +
        "Where Muslims see Jesus as a prophet, Christians confess him as God incarnate. " +
        "This is a deep difference worth honest conversation."
    );
    expect(r.pass).toBe(true);
  });
});
